# Generated by Django 5.2.9 on 2025-12-26 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=16, verbose_name='Class Name')),
                ('shorthand', models.CharField(max_length=3, verbose_name='Class Shorthand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=16, verbose_name='Race Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SquadronMissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('title', models.TextField(verbose_name='Title')),
                ('reward', models.TextField(verbose_name='Reward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SquadronMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('physical_stat', models.IntegerField(verbose_name='Physical Stat')),
                ('mental_stat', models.IntegerField(verbose_name='Mental Stat')),
                ('tactical_stat', models.IntegerField(verbose_name='Tactical Stat')),
                ('chemistry', models.TextField(verbose_name='Chemistry')),
                ('level', models.IntegerField(default=1, help_text='Level can only be between 1 and 60', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('member_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='squadron_calculator.memberclass', verbose_name='Class')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='squadron_calculator.race', verbose_name='Race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SquadronMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('success_chance_message', models.IntegerField(choices=[(0, 'There is little chances that this mission will succeed...'), (1, 'This mission will test the squadron to its limits. Are the risks worth the reward?'), (2, 'This mission will be challenging, but I think our squadron is equal to the task!'), (3, 'This mission is bound to succeed!')], default=0, verbose_name='Success Chance Message')),
                ('required_physical', models.IntegerField(verbose_name='Required Physical Stat')),
                ('required_mental', models.IntegerField(verbose_name='Required Mental Stat')),
                ('required_tactical', models.IntegerField(verbose_name='Required Tactical Stat')),
                ('mission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='squadron_calculator.squadronmissiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
