# Generated by Django 5.2.9 on 2026-04-30 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('condition_proc', models.CharField(choices=[('ACCOMPANYING ARCANIST', 'accompanying an Arcanist'), ('ACCOMPANYING ARCHER', 'accompanying an Archer'), ('ACCOMPANYING CONJURER', 'accompanying a Conjurer'), ('ACCOMPANYING GLADIATOR', 'accompanying a Gladiator'), ('ACCOMPANYING LANCER', 'accompanying a Lancer'), ('ACCOMPANYING MARAUDER', 'accompanying a Marauder'), ('ACCOMPANYING PUGILIST', 'accompanying a Pugilist'), ('ACCOMPANYING ROGUE', 'accompanying a Rogue'), ('ACCOMPANYING THAUMATURGE', 'accompanying a Thaumaturge'), ('ACCOMPANYING SAME CLASS', 'accompanying someone of the same class'), ('ACCOMPANYING DIFF CLASS', 'accompanying someone of a different class'), ('NOT ACCOMPANYING SAME CLASS', 'not accompanying someone of the same class'), ('3 OR MORE SAME CLASS', '3 or more squadrom members are of the same class'), ('ALL DIFF CLASS', 'all squadron members are of a differnet class'), ('ACCOMPANYING AU RA', 'accompanying an Au Ra'), ('ACCOMPANYING ELEZEN', 'accompanying an Elezen'), ('ACCOMPANYING HYUR', 'accompanying a Hyur'), ('ACCOMPANYING LALAFELL', 'accompanying a Lalafell'), ('ACCOMPANYING MIQOTE', "accompanying a Miqo'te"), ('ACCOMPANYING ROEGADYN', 'accompanying a Roegadyn'), ('ACCOMPANYING SAME RACE', 'accompanying someone of the same race'), ('ACCOMPANYING DIFF RACE', 'accompanying someone of a different race'), ('NOT ACCOMPANYING SAME RACE', 'not accompanying someone of the same race'), ('3 OR MORE SAME RACE', '3 or more squadron members are of the same race'), ('ALL DIFF RACE', 'all squadron members are of a different race'), ('ACTIVE', 'an active squadron member'), ('AT OR ABOVE LEVEL', "at or above a duty's recommended level"), ('OVER 50', 'above level 50')], verbose_name='Condition that procs chemistry')),
                ('bonus', models.IntegerField(choices=[(3, '3%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%')], verbose_name='Percentage1')),
                ('to_all', models.BooleanField(default=False)),
                ('reward_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MENTAL', 'Mental'), ('TACTICAL', 'Tactical'), ('EXP', 'Experience'), ('INCREASED RATES', 'increased party chemistry trigger rates'), ('WARFARE OFFENCE', 'chance to receive Contemporary Warfare: Offence'), ('WARFARE DEFENSE', 'chance to receive Contemporary Warfare: Defence'), ('WARFARE MAGICS', 'chance to receive Contemporary Warfare: Magics'), ('DOH MATERIA', 'chance to receive DoH-specific materia'), ('DOL MATERIA', 'chance to receive DoL-specific materia'), ('DOM MATERIA', 'chance to receive DoM-specific materia'), ('TANK MATERIA', 'chance to receive tank-specific materia'), ('PHYSICAL DPS MATERIA', 'chance to receive physical DPS-specific materia'), ('CRYSTAL CLUSTERS', 'chance to receive crystal clusters'), ('GATHERERS SCRIPS', "chance to receive gatherers' scrips"), ('CRAFTERS SCRIPS', "chance to receive crafters' scrips"), ('SEALS', 'chance to receive bonus company seals'), ('MGP', 'chance to receive bonus MGP'), ('GIL', 'chance to receive bonus gil')], verbose_name='Rewards for proccing chemistry')),
                ('priority', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Priority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('reward_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('MENTAL', 'Mental'), ('TACTICS', 'Tactics'), ('EXPERIENCE', 'Experience'), ('INCREASED_CHEMISTRY_TRIGGER_RATE', 'Increased chemistry trigger rate'), ('CONTEMPORARY_WARFARE_OFFENCE', 'Contemporary Warfare: Offence'), ('CONTEMPORARY_WARFARE_DEFENSE', 'Contemporary Warfare: Defense'), ('CONTEMPORARY_WARFARE_MAGICS', 'Contemporary Warfare: Magics'), ('DOH_MATERIA', 'DoH materia'), ('DOL_MATERIA', 'DoL materia'), ('DOM_MATERIA', 'DoM materia'), ('TANK_MATERIA', 'Tank materia'), ('PHYSICAL_DPS_MATERIA', 'Physical DPS materia'), ('CRYSTAL_CLUSTERS', 'Crystal clusters'), ('GATHERERS_SCRIPS', "Gatherers' scrips"), ('CRAFTERS_SCRIPS', 'Crafter Scrips'), ('COMPANY_SEALS', 'Company Seals'), ('MGP', 'MGP'), ('GIL', 'Gil')], verbose_name='Preferred Reward')),
                ('ordering', models.PositiveIntegerField(verbose_name='Ordering of preference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='squadronmember',
            name='chemistry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='squadron_calculator.chemistry', verbose_name='Chemistry'),
        ),
    ]
