# Generated by Django 6.1.1 on 2026-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron_calculator', '0002_chemistry_userpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='bonus',
            field=models.IntegerField(choices=[(3, '3%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%')], verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='condition_proc',
            field=models.CharField(choices=[('ACCOMPANYING ARCANIST', 'Accompanying an Arcanist'), ('ACCOMPANYING ARCHER', 'Accompanying an Archer'), ('ACCOMPANYING CONJURER', 'Accompanying a Conjurer'), ('ACCOMPANYING GLADIATOR', 'Accompanying a Gladiator'), ('ACCOMPANYING LANCER', 'Accompanying a Lancer'), ('ACCOMPANYING MARAUDER', 'Accompanying a Marauder'), ('ACCOMPANYING PUGILIST', 'Accompanying a Pugilist'), ('ACCOMPANYING ROGUE', 'Accompanying a Rogue'), ('ACCOMPANYING THAUMATURGE', 'Accompanying a Thaumaturge'), ('ACCOMPANYING SAME CLASS', 'Accompanying someone of the same class'), ('ACCOMPANYING DIFF CLASS', 'Accompanying someone of a different class'), ('NOT ACCOMPANYING SAME CLASS', 'Not accompanying someone of the same class'), ('3 OR MORE SAME CLASS', '3 or more squadrom members are of the same class'), ('ALL DIFF CLASS', 'All squadron members are of a differnet class'), ('ACCOMPANYING AU RA', 'Accompanying an Au Ra'), ('ACCOMPANYING ELEZEN', 'Accompanying an Elezen'), ('ACCOMPANYING HYUR', 'Accompanying a Hyur'), ('ACCOMPANYING LALAFELL', 'Accompanying a Lalafell'), ('ACCOMPANYING MIQOTE', "Accompanying a Miqo'te"), ('ACCOMPANYING ROEGADYN', 'Accompanying a Roegadyn'), ('ACCOMPANYING SAME RACE', 'Accompanying someone of the same race'), ('ACCOMPANYING DIFF RACE', 'Accompanying someone of a different race'), ('NOT ACCOMPANYING SAME RACE', 'Not accompanying someone of the same race'), ('3 OR MORE SAME RACE', '3 or more squadron members are of the same race'), ('ALL DIFF RACE', 'All squadron members are of a different race'), ('ACTIVE', 'An active squadron member'), ('AT OR ABOVE LEVEL', "At or above a duty's recommended level"), ('OVER 50', 'Above level 50')], verbose_name='Condition that procs chemistry'),
        ),
        migrations.AlterField(
            model_name='squadronmember',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
    ]
