# Generated by Django 6.1.1 on 2026-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadron_calculator', '0003_alter_chemistry_bonus_alter_chemistry_condition_proc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='reward_type',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('MENTAL', 'Mental'), ('TACTICAL', 'Tactical'), ('EXP', 'Experience'), ('INCREASED RATES', 'Increased party chemistry trigger rates'), ('WARFARE OFFENCE', 'Chance to receive Contemporary Warfare: Offence'), ('WARFARE DEFENSE', 'Chance to receive Contemporary Warfare: Defence'), ('WARFARE MAGICS', 'Chance to receive Contemporary Warfare: Magics'), ('DOH MATERIA', 'Chance to receive DoH-specific materia'), ('DOL MATERIA', 'Chance to receive DoL-specific materia'), ('DOM MATERIA', 'Chance to receive DoM-specific materia'), ('TANK MATERIA', 'Chance to receive tank-specific materia'), ('PHYSICAL DPS MATERIA', 'Chance to receive physical DPS-specific materia'), ('CRYSTAL CLUSTERS', 'Chance to receive crystal clusters'), ('GATHERERS SCRIPS', "Chance to receive gatherers' scrips"), ('CRAFTERS SCRIPS', "Chance to receive crafters' scrips"), ('SEALS', 'Chance to receive bonus company seals'), ('MGP', 'Chance to receive bonus MGP'), ('GIL', 'Chance to receive bonus gil')], verbose_name='Rewards for proccing chemistry'),
        ),
        migrations.AlterField(
            model_name='squadronmission',
            name='success_chance_message',
            field=models.IntegerField(choices=[(0, 'There is little Chances that this mission will succeed...'), (1, 'This mission will test the squadron to its limits. Are the risks worth the reward?'), (2, 'This mission will be challenging, but I think our squadron is equal to the task!'), (3, 'This mission is bound to succeed!')], default=0, verbose_name='Success Chance Message'),
        ),
    ]
